// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// read_qmsim_geno
Rcpp::IntegerMatrix read_qmsim_geno(const std::string& file_path, const std::string& geno_mode, int phase_seed);
RcppExport SEXP _HAPTRACE_read_qmsim_geno(SEXP file_pathSEXP, SEXP geno_modeSEXP, SEXP phase_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type geno_mode(geno_modeSEXP);
    Rcpp::traits::input_parameter< int >::type phase_seed(phase_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(read_qmsim_geno(file_path, geno_mode, phase_seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HAPTRACE_read_qmsim_geno", (DL_FUNC) &_HAPTRACE_read_qmsim_geno, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_HAPTRACE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
