# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_qmsim_geno <- function(file_path, geno_mode = "haplotype", phase_seed = 42L) {
    .Call(`_HAPTRACE_read_qmsim_geno`, file_path, geno_mode, phase_seed)
}

